Repository xataio/xata-py, pull requests merged in 2023-10, with the labels that each got.

#176 Make Transaction helper response an object
  tests/integration-tests/helpers_transaction_test.py
  xata/helpers.py
Labels: enhancement, helpers/transactions, tests/integration-tests

#178 Create tranform url helper
  tests/unit-tests/files_transformations_test.py
  xata/api/files.py
Labels: changelog:public, hacktoberfest

#179 Prep release: 1.2.0
  poetry.lock
  pyproject.toml
  xata/client.py
Labels: release
